#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success
checkTagExist mongodb.success
checkTagExist nodejs.success

rootDir=$(rootDir)
# app_path=/opt/rocket
rocketPath=/opt/Rocket.Chat

ufw allow 27017

echo "Installing and tweaking nodejs requirements" | log
installPackage graphicsmagick
waitOrStop 0 "Failed apt install: graphicsmagick"
npm install -g inherits n
n 12.14.0

echo "Preparing mongodb requirements"
sed -i "s/^#  engine:/  engine: mmapv1/"  /etc/mongod.conf
sed -i "s/^#replication:/replication:\n  replSetName: rs01/" /etc/mongod.conf
rm /var/lib/mongodb/mongod.lock
mongod --repair --dbpath /var/lib/mongodb
sleep 5
mongo --eval "printjson(rs.initiate())"

echo "Installing Rocket.Chat app" | log
curlDownload https://releases.rocket.chat/latest/download /tmp/rocket.chat.tgz
waitOrStop 0 "File not downloaded from official source"
tar -xzf /tmp/rocket.chat.tgz -C /tmp
cd /tmp/bundle/programs/server 
npm install
mv /tmp/bundle $rocketPath

echo "Configure and init main app" | log
useradd -M rocketchat
usermod -L rocketchat
chown -R rocketchat:rocketchat $rocketPath
cp -f $rootDir/dev/tweaks/rocketchat.service /lib/systemd/system/
sed -i '/Environment=/s/DOMAIN_PLACEHOLDER/'"${CWM_DISPLAYED_ADDRESS}"':3000/g' /lib/systemd/system/rocketchat.service
systemctl daemon-reload
systemctl enable rocketchat
systemctl start rocketchat

# echo "Adding Loading in Progress screen" | log
# nginxErrorPage=/usr/share/nginx/html/customerror_50x.html
# useFiglet
# printf "<pre align=center>\n" > $nginxErrorPage
# bannerFiglet "Loading in Progress\n Please Wait.\n" >> $nginxErrorPage
# printf "Application and services loading is in progress, process will take a couple of minutes to complete \n\nThank you for your patience.\n\nRefresh page within a couple of minutes for updated status." >> $nginxErrorPage

echo "Configuring nginx" | log
cp -f $rootDir/dev/tweaks/rocketchat.conf /etc/nginx/sites-available/
ln -s /etc/nginx/sites-available/rocketchat.conf /etc/nginx/sites-enabled/
unlink /etc/nginx/sites-enabled/default
sed -i '/Environment=/s/http:\/\/'"${CWM_DISPLAYED_ADDRESS}"':3000/https:\/\/'"${CWM_DISPLAYED_ADDRESS}"'\//g' /lib/systemd/system/rocketchat.service
service nginx restart
waitOrStop 0 "Restart nginx service failed"

echo "Adding descriptions" | log
descriptionAppend "Rocket.chat application directory: ${rocketPath}"
descriptionAppend "Rocket.chat web UI: https://${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "

tagScript success

exit 0