#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success
checkTagExist mongodb.success
checkTagExist nodejs.success

rootDir=$(rootDir)
app_path=/opt/Rockat.Chat
# mongo_url="mongodb://localhost:27017"
mongo_url="mongodb://admin:${ADMINPASSWORD}@localhost:27017"
user_name=rocketchat
app_port=3000
mongo_config=/etc/mongod.conf

echo "Installing and tweaking nodejs requirements" | log
installPackage graphicsmagick
waitOrStop 0 "Failed apt install: graphicsmagick"
npm install -g inherits n
n 12.14.0

echo "Creat app user" | log
useradd -m -U -r -d $app_path $user_name
usermod -a -G $user_name www-data
chmod 750 $app_path

echo "Configuring mongodb for Rocket.Chat" | log
sed -i "s/^#  engine:/  engine: mmapv1/"  $mongo_config
sed -i "s/^#replication:/replication:\n  replSetName: rs01/" $mongo_config

echo "Install main app" | log
curlDownload https://releases.rocket.chat/latest/download $app_path/rocket.chat.tgz
waitOrStop 0 "File not downloaded from official source"
chown -R $user_name:$user_name $app_path/rocket.chat.tgz

su ${user_name} << EOF
cd ${app_path}
tar zxf rocket.chat.tgz
mv bundle Rocket.Chat
cd Rocket.Chat/programs/server
npm install
export PORT=${app_port}
export ROOT_URL="http://0.0.0.0:"${app_port}"/"
export MONGO_URL=${mongo_url}/rocketchat?authSource=admin
EOF

ufw allow $app_port
ufw allow 27017

echo "Installing service" | log
cat << EOF > /etc/systemd/system/rocketchat.service

[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target

[Service]
ExecStart=/usr/local/bin/node ${app_path}/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=${user_name}
Environment=NODE_ENV=production MONGO_URL=${mongo_url}/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=${mongo_url}/local?replicaSet=rs01 ROOT_URL=https://${CWM_SERVERIP} PORT=${app_port}

[Install]
WantedBy=multi-user.target

EOF

systemctl daemon-reload
waitOrStop 0 "Reload systemctl failed"
systemctl start rocketchat
waitOrStop 0 "Start rocketchat service failed"
systemctl enable rocketchat

echo "Adding Loading in Progress screen" | log
nginxErrorPage=/usr/share/nginx/html/customerror_50x.html
useFiglet
printf "<pre align=center>\n" > $nginxErrorPage
bannerFiglet "Loading in Progress\n Please Wait.\n" >> $nginxErrorPage
printf "Application and services loading is in progress, process will take a couple of minutes to complete \n\nThank you for your patience.\n\nRefresh page within a couple of minutes for updated status." >> $nginxErrorPage

echo "Configuring nginx" | log
cp -f $rootDir/tweaks/extras/rocketchat-nginx/rocketchat-nginx-config /etc/nginx/sites-available/rocketchat.conf
# sed -i "s/SERVERIP/${CWM_SERVERIP}/g" /etc/nginx/sites-available/rocketchat.conf
ln -s /etc/nginx/sites-available/rocketchat.conf /etc/nginx/sites-enabled/
unlink /etc/nginx/sites-enabled/default
unlink /etc/nginx/sites-enabled/default-ssl
systemctl reload nginx
waitOrStop 0 "Reload nginx service failed"

descriptionAppend "Rocket.chat application directory: ${app_path}"
descriptionAppend "Rocket.chat IP address: https://${CWM_SERVERIP}"
descriptionAppend "Rocket.chat web UI: https://${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "

tagScript success

exit 0